name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build
        run: |
          npm ci
          npm run build
        # Optional: forces envs even if .env.production is missed
        env:
          VITE_API_BASE_URL: https://adoppet-f6edcyfchphjh3hv.malaysiawest-01.azurewebsites.net/api
          VITE_SOCKET_URL: https://adoppet-f6edcyfchphjh3hv.malaysiawest-01.azurewebsites.net

      - name: Verify baked API base
        run: |
          grep -R "adoppet-f6edcyfchphjh3hv.malaysiawest-01.azurewebsites.net/api" dist && echo "✅ Found"

      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: "/"         # <-- your Vite app is at repo root
          api_location: ""          # <-- no Functions here
          output_location: "dist"   # <-- Vite output
