name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Build the Vite app (this is where VITE_* are baked in)
      - name: Build
        run: |
          npm ci
          npm run build
        # keep these even though you have .env.production; this guarantees correctness
        env:
          VITE_API_BASE_URL: https://adoppet-f6edcyfchphjh3hv.malaysiawest-01.azurewebsites.net/api
          VITE_SOCKET_URL:   https://adoppet-f6edcyfchphjh3hv.malaysiawest-01.azurewebsites.net

      # Quick sanity check so we know the bundle has the right URL
      - name: Verify baked API base
        run: |
          grep -R "adoppet-f6edcyfchphjh3hv.malaysiawest-01.azurewebsites.net/api" dist && echo "✅ Found"

      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"         # <-- REQUIRED (fixes your error)
          app_location: "/"        # repo root contains the Vite app
          api_location: ""         # no Functions in this repo
          output_location: "dist"  # Vite build output
